title: MAMMA's Blog
description: '각종 정보 기록'
logo: logo.png
disqus_shortname: mamma1234
disqus_url: mamma1234@gamil.com
disqus_id: mamma1234
share: true
dropcap: true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''

# remote_theme: hmfaysal/Notepad
remote_theme: mmistakes/minimal-mistakes

url: 'https://mamma1234.github.io' # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: '' # the subpath of your site, e.g. "/blog"

# Owner/author information
owner:
    name: mamma1234
    avatar: mamma1234.jpg
    email: mamma1234@gmail.com
    # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
    description: A person longing for any dream for a long time  resembles that dream at last .
    # Social networking links used in footer. Update and remove as you like.
    #twitter:        hmfaysal
    facebook: daekyu.park.50
    github: mamma1234
    instagram: mamma_amazing
    # For Google Authorship https://plus.google.com/authorship
    #google_plus:    https://plus.google.com/u/0/102602916593522619858

# Analytics and webmaster tools stuff goes here
# google_analytics:   UUA-133319432-1
google_analytics: UUA-133319432-1
#google_verify:

google_tag: GTM-58K8LXF

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true

links:
    - title: Home
      url: /
      external: false
      icon: home
    - title: Featured Posts
      url: /featured
    - title: Tags
      url: /tags
    - title: Categories
      url: /categories
    - title: Notion
      url: https://www.notion.so/invite/70d08f3a6889254b0483fc1f6442e0b9d8d929e5
    - title: Bookmark
      url: /mamma1234.github.io.sub
    - title: Pages
      url: /mamma1234.github.io.pages
    - title: About
      url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Dhaka
future: true
highlighter: pygments
markdown: kramdown
paginate: 10
paginate_path: 'page:num'

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    use_coderay: false

    coderay:
        coderay_line_numbers:
        coderay_line_numbers_start: 1
        coderay_tab_width: 4
        coderay_bold_every: 10
        coderay_css: class

prose:
    rooturl: '_posts'
    siteurl: 'http://mamma1234.github.io/Notepad/'
    relativeLinks: 'http://mamma1234.github.io/Notepad/links.jsonp'
    media: 'images'
    metadata:
        _posts:
            - name: 'published'
              field:
                  label: 'Published'
                  element: 'checkbox'
                  value: 'true'
            - name: 'layout'
              field:
                  element: 'hidden'
                  label: 'Layout'
                  value: 'post'
            - name: 'title'
              field:
                  label: 'Title'
                  element: 'text'
                  value: 'An Awesome Headline!'
            - name: 'description'
              field:
                  element: 'text'
                  label: 'Description'
                  placeholder: 'Enter Post Description'
            - name: 'headline'
              field:
                  element: 'text'
                  label: 'beadline'
                  placeholder: 'Enter Post Headline'
            - name: 'modified'
              field:
                  element: 'text'
                  label: 'Has this page been modified?'
                  placeholder: 'YYYY-MM-DD'
            - name: 'categories'
              field:
                  element: 'multiselect'
                  label: 'Add categories'
                  placeholder: 'Choose categories'
                  value: personal
                  options:
                      - name: 'Personal'
                        value: personal
                      - name: 'Engineering'
                        value: engineering
                      - name: 'Physics'
                        value: physics
                      - name: 'Psychology'
                        value: psychology
                      - name: 'Interesting'
                        value: interesting
                      - name: 'Web-Development'
                        value: webdevelopment
                  alterable: true
            - name: 'tags'
              field:
                  element: 'text'
                  label: 'Tags'
                  placeholder: 'Enter tags, separated by spaces'
            - name: 'imagefeature'
              field:
                  element: 'text'
                  label: 'Featured Image'
                  placeholder: 'somefile.jpg'
            - name: 'mathjax'
              field:
                  element: 'checkbox'
                  label: 'MathJax'
                  value: false
            - name: 'featured'
              field:
                  element: 'checkbox'
                  label: 'Featured?'
                  value: false
            - name: 'comments'
              field:
                  element: 'checkbox'
                  label: 'Comments'
                  value: false

include: ['.htaccess']
exclude:
    [
        'lib',
        'config.rb',
        'Gemfile',
        'Capfile',
        'Gemfile.lock',
        'config',
        'log',
        'Rakefile',
        'Rakefile.rb',
        'tmp',
        'less',
        '*.sublime-project',
        '*.sublime-workspace',
        'test',
        'spec',
        'Gruntfile.js',
        'package.json',
        'node_modules',
    ]
